name: build and release container

on:
  push:
    # branches:
    #  - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    name: build test and release
    runs-on: ubuntu-20.04

    steps:
      - name: Check out main repo
        uses: actions/checkout@v2

      - name: Get the tag version
        id: get_version
        shell: bash
        run: echo "##[set-output name=VERSION;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: metaheed/kolle-ci
          tags: "latest,${{ steps.get_version.outputs.VERSION }}"
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

